swagger: '2.0'
info:
  description: API for getting audit events for users or domains
  version: 1.0.0
  title: CFAL Public API
basePath: /gdc
tags:
  - name: auditEvents
    description: API for Audit Events listing
schemes:
  - https
paths:
  '/account/profile/{userId}/auditEvents':
    get:
      tags:
        - auditEvents
      summary: Get a list of audit events of the given user in current domain.
      description: |-
        Returns a paged list of audit events for a specific user. For more information about audit events, see Auditing Platform Events.
        A domain admin can list audit events for any user in their domain. A user can list only their own events.
      parameters:
        - name: userId
          in: path
          description: The person's public ID
          required: true
          type: string
        - $ref: '#/parameters/offsetParam'
        - $ref: '#/parameters/limitParam'
        - $ref: '#/parameters/fromParam'
        - $ref: '#/parameters/toParam'
        - $ref: '#/parameters/typeParam'
      responses:
        '200':
          description: A list of AuditEvents
          schema:
            $ref: '#/definitions/AuditEvents'
        '400':
          description: Bad request
          schema:
            $ref: '#/definitions/ErrorStructure'
        '401':
          description: Unauthorized
          schema:
            $ref: '#/definitions/ErrorStructure'
        '500':
          description: Internal error
          schema:
            $ref: '#/definitions/ErrorStructure'
  '/domains/{domainId}/auditEvents':
    get:
      tags:
        - auditEvents
      summary: Get a list of audit events for the domain
      description: |-
        Returns a paged list of audit events for a specific domain. For more information about audit events, see Auditing Platform Events.
        You must be a domain admin to perform this operation.
      parameters:
        - name: domainId
          in: path
          description: Domain ID
          required: true
          type: string
        - $ref: '#/parameters/offsetParam'
        - $ref: '#/parameters/limitParam'
        - $ref: '#/parameters/fromParam'
        - $ref: '#/parameters/toParam'
        - $ref: '#/parameters/typeParam'
      responses:
        '200':
          description: A list of AuditEvents
          schema:
            $ref: '#/definitions/AuditEvents'
        '400':
          description: Bad request
          schema:
            $ref: '#/definitions/ErrorStructure'
        '401':
          description: Unauthorized
          schema:
            $ref: '#/definitions/ErrorStructure'
        '500':
          description: Internal error
          schema:
            $ref: '#/definitions/ErrorStructure'
definitions:
  AuditEvent:
    properties:
      id:
        type: string
        example: 123-324-123
        description: The unique ID of the event.
      userLogin:
        type: string
        example: email@gooddata.com
        description: The type of the event.
      occurred:
        type: string
        format: date-time
        description: The timestamp when the event occurred.
      recorded:
        type: string
        format: date-time
        description: The timestamp when the event was recorded by the system (the from and to parameters apply to this value).
      userIp:
        type: string
        example: 127.0.0.1
        description: Public IP of the user who initiated this particular action
      success:
        type: boolean
        example: true
      type:
        type: string
        example: login
        description: Type of the event
      params:
        type: object
        example:
          foo: bar
        description: A string/string map of additional context information.
        additionalProperties:
          type: string
      links:
        type: object
        example:
          profile: /account/profile/abc/auditEvents
        description: A string/string map of the affected resources.
        additionalProperties:
          type: string
    title: JSON representation of one audit event
  AuditEvents:
    title: JSON representation of a list of audit events
    properties:
      events:
        properties:
          items:
            type: array
            items:
              $ref: '#/definitions/AuditEvent'
          paging:
            type: object
            additionalProperties:
              type: string
            example:
              next: /gdc/domains/default/auditEvents?offset=123-324-123
          links:
            type: object
            additionalProperties:
              type: string
            example:
              self: /gdc/domains/default/auditEvents
  ErrorStructure:
    title: Error structure
    properties:
      error:
        properties:
          errorClass:
            type: string
          trace:
            type: string
          message:
            type: string
          component:
            type: string
          errorId:
            type: string
          errorCode:
            type: string
          parameters:
            type: array
            items:
              type: object

parameters:
  offsetParam:
    name: offset
    in: query
    description: The identifier of the first record (for paging)
    required: false
    type: string
  limitParam:
    name: limit
    in: query
    description: The maximum number of records per page
    required: false
    type: integer
    minimum: 1
  fromParam:
    name: from
    in: query
    description: Specify minimal timestamp of audit events to be returned
    required: false
    type: string
    format: date-time
  toParam:
    name: to
    in: query
    description: Specify maximal timestamp of audit events to be returned
    required: false
    type: string
    format: date-time
  typeParam:
    name: type
    in: query
    description: Specify filter on type of events to be returned by this API
    required: false
    type: string
